### ISSUE TITLE
Fault 10: 'BAD_NAME: twitterfilter-19'

### ISSUE THREAD

**Issue by anupkalburgi** [gwu-libraries/social-feed-manager#340]
Has anyone here got this error before? I have tired making changes to the config files that get generated. 
Looks like my process is never getting started at all. 

According to supervisord Docs, (wrt proxy.supervisor.reloadConfig() ) reload only picks up  changes to already existing process, but in this case when we add a new filter we are generating a new config file every time so how is that handled. Or am i missing something very obvious here.   Like we have to start a supervisor process before hand ?

Internal Server Error: /admin/ui/twitterfilter/add/
Traceback (most recent call last):
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/contrib/admin/options.py", line 465, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1164, in add_view
    self.save_model(request, new_object, form, False)
  File "/home/anupk/sfm/social-feed-manager/sfm/ui/admin.py", line 50, in save_model
    super(TwitterFilterAdmin, self).save_model(request, obj, form, change)
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/contrib/admin/options.py", line 893, in save_model
    obj.save()
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/anupk/sfm/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/anupk/sfm/social-feed-manager/sfm/ui/models.py", line 441, in call_create_conf
    ui.utils.add_process_group(instance.id)
  File "/home/anupk/sfm/social-feed-manager/sfm/ui/utils.py", line 120, in add_process_group
    proxy.supervisor.addProcessGroup(processname)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/home/anupk/sfm/lib/python2.7/site-packages/supervisor/xmlrpc.py", line 475, in request
    return u.close()
  File "/usr/lib64/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 10: 'BAD_NAME: twitterfilter-19'>
[15/May/2015 15:07:22] "POST /admin/ui/twitterfilter/add/ HTTP/1.1" 500 201792

**Comment by anupkalburgi** [comment]
Sorry please ignore this. I got this working.

**Comment by kerchner** [comment]
Hi @anupkalburgi - just curious, which institution are you working with?  Or are you using SFM on a personal basis?  We're happy to see that you're interested in using SFM and would like to learn about how others are using it!

**Comment by kerchner** [comment]
Closing as per author's note above.

**Comment by anupkalburgi** [comment]
I am from George Mason University Data Services unit at Fenwick Library . We are trying to make use of this to collect streams.
